### PR TITLE
This makes beatmap behaves like a beatgrid when constant tempo preference is true

### PR DESCRIPTION
**Pull request by crisclacerda**
This makes beatmap behaves like a beatgrid when constant tempo preference is true and also fix scons build.

### CODE REVIEW

**Comment by JaviVilarroig** [comment]
Hi Cristiano. 
Sorry I didn't see that until now. I'm not used to github interface :S
I don't use Scons any more so I'm not going to test the fix, but it looks simple and right :)
About the constant tempo part. I'm not sure if it's a good solution. It's It just fixes the get getBPM part of the issue but the beats are left exactly as they are so there is a potential disagreement between the tempo shown in the screen and how the beats are painted in the waveform.
Have you think on that? Probably the opinion from the developers team can have a value.

**Comment by crisclacerda** [comment]
No worries.
Yes, that's something @be-ing have posted on [Zulip:](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/support.20for.20bar.20and.20phrase.20info.20and.20variable.20BPM)

"For a roadmap for #2512, I propose to use the existing "assume constant tempo" preference option to generate a constant tempo beatgrid functionally equivalent to the old BeatGrid class but using the new Beats API. This will allow us to merge it to master sooner."

That's what I have tried to implement here. I have tested this on a couple of tracks and it worked nice, some tracks that were problematic on the old beat grid got them painted right now.

The problem with the beatmap is that without fixing the tempo, some tracks that should have constant tempo actually display the tempo with small fluctuations while the tracks play, I think we should in fact just ignore this fluctuation and be seems to agree on that.

But one thing that I haven't put much thought here is on converting the old beat grid into the new beat map format. Especially tracks that were analyzed with the fast option and do not have all beat positions will not have beat grid painted for the whole track.

Please give this a spin and see if it works nicely for you too and feel free to just ignore and close this PR, if you don't like how it behaves.
Also, I haven't had the time to test your new patches on #2512 yet.

**Comment by JaviVilarroig** [comment]
> No worries.
> Yes, that's something @Be-ing have posted on [Zulip:](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/support.20for.20bar.20and.20phrase.20info.20and.20variable.20BPM)
> 
> "For a roadmap for [mixxxdj#2512](https://github.com/mixxxdj/mixxx/pull/2512), I propose to use the existing "assume constant tempo" preference option to generate a constant tempo beatgrid functionally equivalent to the old BeatGrid class but using the new Beats API. This will allow us to merge it to master sooner."
> 
> That's what I have tried to implement here. I have tested this on a couple of tracks and it worked nice, some tracks that were problematic on the old beat grid got them painted right now.
> 
> The problem with the beatmap is that without fixing the tempo, some tracks that should have constant tempo actually display the tempo with small fluctuations while the tracks play, I think we should in fact just ignore this fluctuation and be seems to agree on that.
> 
> But one thing that I haven't put much thought here is on converting the old beat grid into the new beat map format. Especially tracks that were analyzed with the fast option and do not have all beat positions will not have beat grid painted for the whole track.
> 
> Please give this a spin and see if it works nicely for you too and feel free to just ignore and close this PR, if you don't like how it behaves.
> Also, I haven't had the time to test your new patches on [mixxxdj#2512](https://github.com/mixxxdj/mixxx/pull/2512) yet.

Ok. Let's use this fix to see if it's enough to solve the problem on constant tempo tracks. 
Can you please take a look at the conflict? When fixed I will merge it.

**Comment by JaviVilarroig** [comment]
I wanted to use your code so finally I did the conflict resolution.

**Pull request merged**
